# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUXSWnnZPy04WAsRas21rrz7ttTrH4ht
"""

# ============================================================
# INSTALL
# ============================================================


import pandas as pd
import numpy as np
import psycopg2
from datetime import datetime, timedelta
import re

import os

# ============================================================
# CONFIGURATION
# ============================================================
# Get project root directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))

yesterday = (datetime.now() - timedelta(days=1)).strftime("%d-%m-%Y")
RAW_FILE_PATH = os.path.join(BASE_DIR, "statement_file", "qualifier_output", f"{yesterday}_ruled.csv")

from dotenv import load_dotenv

# Get project root directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))

# Load .env file
load_dotenv(os.path.join(BASE_DIR, ".env"))

# ============================================================
# DATABASE CONFIG
# ============================================================

DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")

# ============================================================
# LOAD RAW
# ============================================================
raw_df = pd.read_csv(RAW_FILE_PATH)

file_date = datetime.strptime(
    re.search(r'(\d{2}-\d{2}-\d{4})', RAW_FILE_PATH).group(1),
    "%d-%m-%Y"
).date()

raw_df['date'] = file_date
raw_df['Full_Member_ID'] = raw_df['hhid'].astype(str) + raw_df['member_id'].astype(str)

# ============================================================
# LOAD REGION FROM DATABASE
# ============================================================


conn = psycopg2.connect(
    host=DB_HOST,
    port=DB_PORT,
    dbname=DB_NAME,
    user=DB_USER,
    password=DB_PASSWORD
)

query = """
SELECT
    h.hhid,
    m.member_code,
    m.gender,
    city,
    region,
    DATE_PART('year', AGE(CURRENT_DATE, m.dob)) AS age
FROM households h
JOIN members m ON h.id = m.household_id
ORDER BY h.hhid, m.member_code;
"""

db_df = pd.read_sql(query, conn)

conn.close()

# IMPORTANT: deduplicate HHID → region mapping
master_df = db_df[['hhid','region']].drop_duplicates()

# rename to match your pipeline
master_df.rename(columns={'region':'City_group'}, inplace=True)

# ============================================================
# FIX: ALIGN HHID DATATYPE BEFORE MERGE
# ============================================================
raw_df['hhid'] = raw_df['hhid'].astype(str)
master_df['hhid'] = master_df['hhid'].astype(str)

# ============================================================
# MERGE (ONLY ONCE)
# ============================================================
raw_df = raw_df.merge(master_df, on='hhid', how='left')

missing = raw_df['City_group'].isna().sum()
print("Missing region:", missing)

raw_df['City_group'] = raw_df['City_group'].fillna('Unknown')

print("Valid rows after DB region mapping:", len(raw_df))

# ============================================================
# CHANNEL MAP
# ============================================================
channelid_map = {
    1:"FirstNewsChannel",2:"PublicTV",3:"ShantTV",
    4:"ArmeniaTV",5:"KentronTvHD",7:"DarTV",
    8:"MIRTV",10:"NurTV",11:"BoonTv",
    12:"TV5",13:"NorHayastan",14:"FreeNews", 15:"ATV"
}

raw_df['channel_Name'] = raw_df['channelid'].map(channelid_map)

# ============================================================
# GENRE MAP
# ============================================================
genre_map = {
    "FirstNewsChannel":"News","FreeNews":"News",
    "PublicTV":"GEC","ShantTV":"GEC","ArmeniaTV":"GEC",
    "KentronTvHD":"GEC","TV5":"GEC","NorHayastan":"GEC","MIRTV":"GEC",
    "NurTV":"Others","BoonTv":"Others","DarTV":"Others", "ATV":"GEC"
}

raw_df['Genre_Capping'] = raw_df['channel_Name'].map(genre_map)

# ============================================================
# PER MEMBER ACTUAL DURATION
# ============================================================
indi_day = (
    raw_df
    .groupby(['City_group','Full_Member_ID','channelid','channel_Name','Genre_Capping'])['duration_seconds']
    .sum()
    .reset_index(name='Actual_Duration')
)

viewer_count = (
    raw_df
    .groupby(['City_group','channelid'])['Full_Member_ID']
    .nunique()
    .reset_index(name='uniqueviewercount')
)

p_stats = (
    indi_day
    .groupby(['City_group','channelid'])['Actual_Duration']
    .agg(
        P95=lambda x: int(np.percentile(x,95)),
        P99=lambda x: int(np.percentile(x,99))
    )
    .reset_index()
)


cap_df = (
    indi_day
    .merge(viewer_count, on=['City_group','channelid'])
    .merge(p_stats, on=['City_group','channelid'])
)


# ============================================================
# APPLY CAPS
# ============================================================
cap_df['absolute cap sec'] = cap_df['Genre_Capping'].map(
    {'GEC':5400,'News':3600,'Others':3600}
)

cap_df['low_sample_cap sec'] = cap_df['absolute cap sec']

excluded_channels = {
    'FirstNewsChannel','PublicTV',
    'KentronTvHD','ArmeniaTV','ShantTV','ATV'
}

def final_target(r):
    if r['channel_Name'] in excluded_channels:
        return r['Actual_Duration']
    if r['uniqueviewercount'] < 5:
        return 0
    return min(r['Actual_Duration'], r['P95'], r['absolute cap sec'])

cap_df['Target_Duration'] = cap_df.apply(final_target, axis=1)
cap_df['Capped Value'] = cap_df['Target_Duration']


cap_df['Cut_Required'] = (
    cap_df['Actual_Duration'] - cap_df['Target_Duration']
)

cap_df['Rule_Label'] = np.where(
    cap_df['channel_Name'].isin(excluded_channels),
    'Excluded channel – No cap',
    np.where(
        cap_df['uniqueviewercount'] < 5,
        'Low sample (<5) → Zero',
        'P95 + Absolute cap'
    )
)

# ============================================================
# SPLIT 30-MIN + STRICT MIDNIGHT
# ============================================================
split_rows = []

for _, row in raw_df.iterrows():

    start = float(row['start_time_secs'])
    remaining = float(row['duration_seconds'])

    while remaining > 0:

        seconds_to_midnight = 86400 - (start % 86400)
        seconds_to_30 = 1800 - (start % 1800)

        chunk = min(remaining, seconds_to_midnight, seconds_to_30)

        new_row = row.copy()
        new_row['start_sec'] = start
        new_row['end_sec'] = start + chunk
        new_row['Original_Split_Duration'] = chunk
        new_row['duration_seconds'] = chunk

        split_rows.append(new_row)

        start += chunk
        remaining -= chunk

split_df = pd.DataFrame(split_rows).reset_index(drop=True)




# ============================================================
# DAYPART MASTER (INTERNAL – NO EXTERNAL FILE)
# ============================================================

daypart_data = [
    (7200,9000,1,"Not Important",3),
    (9000,10800,2,"Not Important",3),
    (10800,12600,3,"Not Important",3),
    (12600,14400,4,"Not Important",3),
    (14400,16200,5,"Not Important",3),
    (16200,18000,6,"Not Important",3),
    (18000,19800,7,"Not Important",3),
    (19800,21600,8,"Not Important",3),
    (21600,23400,9,"Not Important",3),
    (23400,25200,10,"Not Important",3),
    (25200,27000,11,"Not Important",3),
    (27000,28800,12,"Not Important",3),
    (28800,30600,13,"Less Important",2),
    (30600,32400,14,"Less Important",2),
    (32400,34200,15,"Less Important",2),
    (34200,36000,16,"Less Important",2),
    (36000,37800,17,"Less Important",2),
    (37800,39600,18,"Less Important",2),
    (39600,41400,19,"Less Important",2),
    (41400,43200,20,"Less Important",2),
    (43200,45000,21,"Less Important",2),
    (45000,46800,22,"Less Important",2),
    (46800,48600,23,"Less Important",2),
    (48600,50400,24,"Less Important",2),
    (50400,52200,25,"Less Important",2),
    (52200,54000,26,"Less Important",2),
    (54000,55800,27,"Less Important",2),
    (55800,57600,28,"Important",1),
    (57600,59400,29,"Important",1),
    (59400,61200,30,"Important",1),
    (61200,63000,31,"Important",1),
    (63000,64800,32,"Important",1),
    (64800,66600,33,"Important",1),
    (66600,68400,34,"Important",1),
    (68400,70200,35,"Important",1),
    (70200,72000,36,"Important",1),
    (72000,73800,37,"Important",1),
    (73800,75600,38,"Important",1),
    (75600,77400,39,"Important",1),
    (77400,79200,40,"Important",1),
    (79200,81000,41,"Important",1),
    (81000,82800,42,"Important",1),
    (82800,84600,43,"Important",1),
    (84600,86400,44,"Important",1),
    (86400,88200,45,"Less Important",2),
    (88200,90000,46,"Less Important",2),
    (90000,91800,47,"Not Important",3),
    (91800,93600,48,"Not Important",3),
]

daypart_df = pd.DataFrame(
    daypart_data,
    columns=["Start Time","End Time","DP ID","Priorities","priorties_ID"]
)

# ============================================================
# ASSIGN DAYPART
# ============================================================

start_mod = split_df['start_sec'] % 86400

# shift 00:00–02:00 to 86400+ range (because your day starts at 02:00)
start_mod = np.where(start_mod < 7200,
                     start_mod + 86400,
                     start_mod)

split_df['start_sec_mod'] = start_mod

def assign_daypart(sec):
    match = daypart_df[
        (daypart_df['Start Time'] <= sec) &
        (daypart_df['End Time'] > sec)
    ]
    if not match.empty:
        r = match.iloc[0]
        return pd.Series([r['DP ID'], r['Priorities'], r['priorties_ID']])
    return pd.Series([None, None, None])

split_df[['DP ID','Priorities','priorties_ID']] = (
    split_df['start_sec_mod'].apply(assign_daypart)
)

# ============================================================
# MERGE CAP DATA
# ============================================================
split_df = split_df.merge(
    cap_df[['Full_Member_ID','channelid',
            'Actual_Duration','Target_Duration',
            'Cut_Required','Genre_Capping',
            'Rule_Label','absolute cap sec',
            'low_sample_cap sec',
            'P99','Capped Value']],
    on=['Full_Member_ID','channelid'],
    how='left'
)


# ============================================================
# FINAL DURATION FLAG BEFORE TRIM
# ============================================================

split_df['clipping require'] = split_df['Cut_Required'] > 0
split_df['Case_Number'] = 0   # default = no clipping

# ============================================================
# CREATE BEFORE-TRIM AUDIT SHEET (CORRECT TIME FORMAT)
# ============================================================

split_before_trim = split_df.copy()

# Proper clock conversion (same logic as final sheet)
def sec_to_clock_before(sec):
    sec = int(sec % 86400)
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    return f"{h:02d}:{m:02d}:{s:02d}"

def sec_to_hms_before(sec):
    sec = int(sec)
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    return f"{h:02d}:{m:02d}:{s:02d}"

# rebuild time columns BEFORE trimming
split_before_trim['start_time'] = split_before_trim['start_sec'].apply(sec_to_clock_before)

split_before_trim['end_time'] = (
    split_before_trim['start_sec'] +
    split_before_trim['duration_seconds']
).apply(sec_to_clock_before)

split_before_trim['duration'] = (
    split_before_trim['duration_seconds']
    .apply(sec_to_hms_before)
)

# ============================================================
# TRIMMING RULE WITH CASE IDENTIFICATION
# APPLY ONLY IF clipping require == TRUE
# ============================================================

for (member, channel), group in split_df.groupby(['Full_Member_ID','channelid']):

    cut_needed = group['Cut_Required'].iloc[0]
    clipping_flag = group['clipping require'].iloc[0]

    # ---- Skip if no clipping required ----
    if (pd.isna(cut_needed) or cut_needed <= 0) or (clipping_flag != True):
        continue

    group_sorted = group.sort_values(
        ['priorties_ID','start_sec'],
        ascending=[False, False]
    )

    # ================= CASE 4 =================
    if len(group_sorted) == 1:

        idx = group_sorted.index[0]

        original_start = split_df.at[idx, 'start_sec']
        original_duration = split_df.at[idx, 'duration_seconds']

        cut_amt = min(original_duration, cut_needed)

        shift = cut_amt / 2

        split_df.at[idx, 'start_sec'] = original_start + shift
        split_df.at[idx, 'duration_seconds'] = original_duration - cut_amt
        split_df.at[idx, 'end_sec'] = (
            split_df.at[idx, 'start_sec'] +
            split_df.at[idx, 'duration_seconds']
        )

        split_df.loc[group.index, 'Case_Number'] = 4
        continue

    # ================= MULTI-BLOCK CASES =================
    cut_positions = []

    for idx in group_sorted.index:

        if cut_needed <= 0:
            break

        available = split_df.at[idx, 'duration_seconds']
        cut_amt = min(available, cut_needed)

        if cut_amt > 0:
            cut_positions.append(idx)

        split_df.at[idx, 'duration_seconds'] -= cut_amt
        split_df.at[idx, 'end_sec'] = (
            split_df.at[idx, 'start_sec'] +
            split_df.at[idx, 'duration_seconds']
        )

        cut_needed -= cut_amt

    # ---- Identify Case Type ----
    if len(cut_positions) == 1:
        cut_idx = cut_positions[0]
        position_rank = group_sorted.index.get_loc(cut_idx)

        if position_rank == 0:
            case = 2   # last block
        elif position_rank == len(group_sorted) - 1:
            case = 1   # first block
        else:
            case = 3   # middle block
    else:
        case = 3

    split_df.loc[group.index, 'Case_Number'] = case

# ============================================================
# FINAL DURATION
# ============================================================
split_df['Final_Duration'] = split_df['duration_seconds']
split_df['clipping require'] = split_df['Cut_Required'] > 0

# ============================================================
# REBUILD TIME COLUMNS
# ============================================================
def sec_to_clock(sec):
    sec = int(sec % 86400)
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    return f"{h:02d}:{m:02d}:{s:02d}"

def sec_to_hms(sec):
    sec = int(sec)
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    return f"{h:02d}:{m:02d}:{s:02d}"

split_df['start_time'] = split_df['start_sec'].apply(sec_to_clock)
split_df['end_time'] = (
    split_df['start_sec'] + split_df['Final_Duration']
).apply(sec_to_clock)

split_df['duration'] = split_df['Final_Duration'].apply(sec_to_hms)

# ============================================================
# CITY WISE SUMMARY
# ============================================================

split_df['Before_Duration'] = split_df['Original_Split_Duration']
split_df['After_Duration'] = split_df['Final_Duration']

city_summary = (
    split_df
    .groupby(['City_group'])
    .agg(
        Before_Total=('Before_Duration','sum'),
        After_Total=('After_Duration','sum'),
        Before_Min_Start=('start_sec','min'),
        Before_Max_End=('end_sec','max'),
        After_Min_Start=('start_sec','min'),
        After_Max_End=('Final_Duration',
                       lambda x: (split_df.loc[x.index,'start_sec'] + x).max())
    )
    .reset_index()
)

city_summary['Difference'] = (
    city_summary['Before_Total'] - city_summary['After_Total']
)

# ============================================================
# CHANNEL WISE SUMMARY
# ============================================================

channel_summary = (
    split_df
    .groupby(['channel_Name'])
    .agg(
        Before_Total=('Before_Duration','sum'),
        After_Total=('After_Duration','sum'),
        Before_Min_Start=('start_sec','min'),
        Before_Max_End=('end_sec','max'),
        After_Min_Start=('start_sec','min'),
        After_Max_End=('Final_Duration',
                       lambda x: (split_df.loc[x.index,'start_sec'] + x).max())
    )
    .reset_index()
)

channel_summary['Difference'] = (
    channel_summary['Before_Total'] - channel_summary['After_Total']
)


# ============================================================
# PREPARE FINAL REQUIRED OUTPUT STRUCTURE
# ============================================================

# Replace duration_seconds with final trimmed duration
split_df['duration_seconds'] = split_df['Final_Duration']

# Keep only required columns in correct order
final_output_df = split_df[
    [
        'date',
        'hhid',
        'tv_set',
        'member_id',
        'channel',
        'start_time',
        'end_time',
        'duration',
        'duration_seconds',
        'type',
        'channelid'
    ]
].copy()

# ============================================================
# SAVE AS SINGLE CSV
# ============================================================

OUTPUT_FILE = RAW_FILE_PATH.replace(".csv", "_PROCESSED.csv")

final_output_df.to_csv(OUTPUT_FILE, index=False)

print(" PROCESSED CSV GENERATED:", OUTPUT_FILE)

